version: "3.8"

services:
  api:
    build: api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
  postgres:
    build: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=books
    ports:
      - "5433:5432"
    volumes:
      - db-data:/postgres-data

volumes:
  db-data: